### ISSUE TITLE
After an unsubscribe on result$ mutation, mutation is no longer working

### ISSUE THREAD

**Issue by ExFlo** [ngneat/query#82] opened 2023-01-27 20:49 UTC
### Which @ngneat/query-* package(s) are the source of the bug?

query

### Is this a regression?

No

### Description

Hi
To reproduce create a mutation using the service, subscribe to the result$, unsubscribe to it, resubscribe --> all I receive is only a loading result.
My use case is I want to be able to create the mutation in a service and use it in multiple component as I want but after the first unsubscribe I am no longer able to use the mutation. 
BR
Florent

### Please provide a link to a minimal reproduction of the bug

https://github.com/ngneat/query/pull/81

### Please provide the exception or error you saw

```true
After a unsubscribe to a result$ mutation the mutation is not longer working and stay in a loading state (as if the observable is no longer subscribe) even if a valid subscription is still on.
```

### Do you want to create a pull request?

Yes

**Comment by ExFlo** [comment] 2023-02-06 10:10
hi @NetanelBasal  I created a codesandbox to reproduce.
[here](https://codesandbox.io/s/stupefied-lamport-0bj3z8?file=/src/app/app.component.ts)
the mutation add todo (and the button) is working until you unsubscribe once to the results$ after it is no longer working.
BR
Florent

**Comment by luii** [comment] 2023-06-23 08:13
@ExFlo Did you already solve this issue? If so, how did you do it?

**Comment by ExFlo** [comment] 2023-06-26 09:11
@luii  Hi my current workaround is to create the mutation everytime, everywhere I need it. Instead of sharing it in service, I create it in every component I need it...

**Comment by luii** [comment] 2023-06-26 11:02
Just so that i better understand the problem, why is it necessary to share the mutation (or the result$ observable)? Could you give me an example where this would make sense - doesnt need to be code though.

What first comes to mind is multicasting (turning cold observables into hot ones) the `result$` observable so that as long as you want the `result$` is subscribed to and getting updates which are pushed into an replay subject from which participants could (un)subscribe.

**Comment by luii** [comment] 2023-06-29 06:35
@NetanelBasal Then i would say that we close this Issue since it's working as intended

**Comment by NetanelBasal** [comment] 2023-06-29 06:38
Yes. TBH I don't see any advantage of using useMutation, and I'm not using it either.

**Comment by NetanelBasal** [comment] 2023-06-29 06:39
See https://github.com/ngneat/query#mutation-result

**Closed by NetanelBasal** 2023-06-29 06:38 UTC
